[package]
name = "pbmetric"
version = "0.1.0"
authors = ["Min Kim <msk@dolbo.net>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = "2"
chrono = "0.4"
directories = "2"
graphql_client = "0.9"
gitlab = "0.1209"
lettre = "0.9.2"
lettre_email = "0.9.2"
maplit = "1"
regex = "1"
reqwest = "0.10"
serde = { version = "1",  features = ["derive"] }
toml = "0.5"
walkdir = "2"
