[package]
name = "pbmetric"
version = "0.3.0"
authors = ["Min Kim <msk@dolbo.net>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = "2"
chrono = "0.4"
directories = "3"
graphql_client = "0.9"
lettre = "0.9.3"
lettre_email = "0.9.4"
regex = "1"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1",  features = ["derive"] }
toml = "0.5"
walkdir = "2"
