[package]
name = "pbmetric"
version = "0.1.0"
authors = ["Min Kim <msk@dolbo.net>"]
edition = "2018"

[dependencies]
clap = "2"
chrono = "0.4"
directories = "2"
gitlab = { git = "https://gitlab.kitware.com/msk/rust-gitlab", branch = "id-hash" }
maplit = "1"
regex = "1"
serde = { version = "1",  features = ["derive"] }
toml = "0.5"
walkdir = "2"
